### PR TITLE
Conn redesigning

### PR DESCRIPTION
**Pull request by WEB3-GForce**
@bford
@dyv
@iuliatamas

The changes made are two fold:
    - Moving conn.go from coco to coco/conn and breaking up the file so that different pieces (like
      the interfaces and implementations) are in different files
    - Making a ConnManager. The insurance policy module will reference servers by their public keys.  
       Hence, I need a wrapper over the connections to be able to map public keys to connections.

I've created a GoConnManager which should suffice for testing purposes of the life insurance policy.

Dylan and Iulia, I have not removed the file from coco so as not to break your current code. If you like the divisions, we can use the new conn directory. Otherwise, I can just keep my life-insurance specific code.

### CODE REVIEW

**Comment by dyv** [comment]
Hi Will, thanks for taking initiative on this. Iulia and I were about to go through a refactor of the coco repository and split it up into packages as well. The one thing I am hesitant about is this new ConnManager. I don't think that we want to introduce keys and crypto into the connection package itself. The idea is that conn is just responsible just for the sending and receiving of data (abstracting away the network layer). I am hesitant on adding this dependency on crypto and associating a crypto key with specific connection. In my mind that seems more like application logic which should be kept in the "Host" structures (which will be moved soon to its own package).

Looking forward to hearing what you think.

**Comment by WEB3-GForce** [comment]
I think it could go in either or. My initial idea about including it in the Conn package was because of its close relationship to the Conn code. It serves primarily as a wrapper so that the life insurance protocol would not need to worry about mapping public keys to connections. If you prefer, I can go ahead and create a host package and put it there.

**Comment by WEB3-GForce** [comment]
I created a new folder called connMan to keep the manager code. Should be ready for merge.

Dylan, Iulia, if the work I did splitting conn into its own folder is good, I can go ahead and merge this pull request. If you all would prefer to refactor it yourselves, I can open up a new pull request with just the code for the connManager.

**Comment by dyv** [comment]
Making a new pull request with just the conn manager would be great. I have also noticed that the conn code has changed since the version you are working with. The master branch hasn't been kept fully up to date with all the changes that we have been doing in the coco fork of the repository (dyv/prifi). We are going to merge the pull request now.

**Comment by WEB3-GForce** [comment]
K, sounds good.

**Pull request closed without merging**
